fitters/runners/bootstrappers return FitModel/Result objects
esheldon/ngmix pull request #143
Opened 2021-03-12 19:27 UTC by esheldon

This was suggested by @beckermr 

TODO

- [ ] make the psf runners/bootstrappers return results/lists of results.  Only set result if requested (old behavior)
- [ ] docs
- [ ] update examples
- [ ] port over metadetect

2021-03-12 23:12 UTC, beckermr commented on ngmix/metacal/bootstrap.py
> +        # resdict[key] = runner.get_result()
remove this comment

2021-03-12 23:18 UTC, beckermr requested changes
My main comment is that if we are going to do this, we need a FitResult base class that every fitter uses. Probably a similar one for the Galsim stuff.

2021-03-13 12:11 UTC, esheldon commented
There are no required methods.  For example the gaussmom result is a pure dictionary.  Also the teamplate fitters return `FitModel` that, while they have methods that are used during fitting, are not useful for the end user.

So the base class would literally by
```python
class FitResult(dict):
    pass
```
For this reason I decided not to use a base class.  But we can if you think it is better.

2021-03-13 12:55 UTC, beckermr commented
Hmmmm ok. Let me look again.

2021-03-15 18:07 UTC, beckermr commented
I see your point on little to few shared methods. The only last bit to consider is if we'd ever want to right code that generically processes the results of fits, e.g.

```
if isinstance(blah, ngmix.FitResult):
    # do something
```

Right now, this won't be possible because the generic base class is absent. 

We could use a generic base class even if it only identifies the kind of thing each object is.

2021-03-15 18:52 UTC, esheldon commented
Yeah, I know what you mean.  I used to use that pattern a lot.

Generally pythonistas don't recommend using isinstance any more because of "easier to ask for forgiveness than permission"

In that vein, we advertise that we return a dict-like, and if they want to test for some feature in the returned value they do

```python
res = fitter.go(obs)
try:
    gm = res.get_gmix()
    # do something
except:
    # do something else
```

2021-03-15 19:13 UTC, beckermr commented
OK shrug. Whatever makes you happiest! :)

2021-03-15 19:13 UTC, beckermr approved these changes

2021-03-15 19:18 UTC, esheldon commented
I don't really care either way, just following advice of experts

2021-03-15 19:21 UTC, esheldon commented
If you feel strongly, go ahead and modify the PR

2021-03-15 19:22 UTC, beckermr commented
Nope no worries from me at all! Merge away!

2021-03-15 22:11 UTC, merged