TST added test for speed of prepsf moments
esheldon/ngmix pull request #216
Opened 2022-03-18 21:33 UTC by beckermr

This PR is documenting the speed of the code before my other changes to ensure no regressions.

2022-04-29 11:59 UTC, beckermr commented
This one is ready for review @esheldon!

2022-04-29 14:14 UTC, esheldon requested changes
We should also have a speedup test for metacal, asserting it is faster by X, to justify the change.

2022-04-30 14:41 UTC, beckermr commented on ngmix/tests/test_prepsfmom.py
> +    assert dt3/nfit < dt2
```suggestion
    assert dt3/nfit < dt2*0.6
```

2022-05-02 14:48 UTC, esheldon commented
what about for metacal?  Is there an important and predictable speedup for this caching?

2022-05-02 15:22 UTC, beckermr commented
The speedup comes from caching the galsim interpolated image object of the original image. It's FFT gets cached internally by galsim and this saves a bunch of time in generating the different metacal images at each color.

2022-06-19 12:14 UTC, beckermr commented
I need to increase the digits on the jacobian repr for this one.

2022-06-19 19:16 UTC, beckermr commented
ok @esheldon This PR is ready to go. I added a test showing the ~30% gains from caching for mdet-sized images.

2022-06-21 13:14 UTC, esheldon approved these changes

2022-06-21 13:18 UTC, merged